/**
 * Deterministic seed generator. Emits `seed.sql` as `COPY ... FROM stdin` blocks
 * (not per-row INSERTs) so millions of reservation rows load fast.
 *
 * Deterministic by design: a fixed-seed RNG means the same inputs always produce
 * byte-identical output, so the seed's content hash is stable and can tag the image.
 * The seed is a regenerable single-state SNAPSHOT — never an accumulating delta.
 *
 * Prod-shape is the point: the seasonal booking curve (near-full Jul/Aug, ramping
 * to summer, closed Dec/Jan) gives date-range predicates very different selectivity
 * by month, and the skewed grade distribution gives the grade index a realistic
 * n_distinct/MCV shape. Those distributions are what drive planner choices.
 */

import { once } from "node:events";
import { createWriteStream } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ---- Parameters (env-overridable; defaults produce ~2-3M reservations) --------

const PARK_COUNT = Number(process.env.SEED_PARKS ?? 40);
const PITCHES_MIN = Number(process.env.SEED_PITCHES_MIN ?? 500);
const PITCHES_MAX = Number(process.env.SEED_PITCHES_MAX ?? 2000);
const SEASONS = (process.env.SEED_SEASONS ?? "2023,2024,2025").split(",").map((y) => Number(y.trim()));
const RNG_SEED = Number(process.env.SEED_RNG ?? 0x5eed);

const MODELS = ["Alpine", "Biscay", "Coastline", "Dorset", "Elgin", "Fairway", "Grasmere", "Havana", "Ionian", "Jasmine"];

// Grade distribution — deliberately skewed so van_grade has a realistic MCV shape
// (savers/bronze common, platinum rare). Cumulative weights.
const GRADE_WEIGHTS: Array<[string, number]> = [
  ["saver", 0.35],
  ["bronze", 0.3],
  ["silver", 0.2],
  ["gold", 0.12],
  ["platinum", 0.03],
];

// Monthly booking weight (1-indexed month → probability a slot is taken).
// Closed Dec/Jan (0); near-full Jul/Aug; ramps up to and down from summer.
const MONTH_WEIGHT: Record<number, number> = {
  1: 0.0,
  2: 0.18,
  3: 0.28,
  4: 0.42,
  5: 0.58,
  6: 0.78,
  7: 0.95,
  8: 0.97,
  9: 0.68,
  10: 0.42,
  11: 0.22,
  12: 0.0,
};

// Stay lengths in nights, weighted toward a week. Cumulative.
const STAY_LENGTHS: Array<[number, number]> = [
  [3, 0.2],
  [4, 0.15],
  [7, 0.45],
  [10, 0.12],
  [14, 0.08],
];

// ---- Seeded RNG (mulberry32) --------------------------------------------------

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rng = mulberry32(RNG_SEED);

const randInt = (min: number, max: number): number => min + Math.floor(rng() * (max - min + 1));

function weightedPick<T>(table: Array<[T, number]>): T {
  const r = rng();
  let acc = 0;
  for (const [value, weight] of table) {
    acc += weight;
    if (r < acc) return value;
  }
  return table[table.length - 1][0];
}

// ---- Date helpers (UTC, no time component) ------------------------------------

const DAY_MS = 86_400_000;

const fmtDate = (d: Date): string => d.toISOString().slice(0, 10);

const addDays = (d: Date, n: number): Date => new Date(d.getTime() + n * DAY_MS);

// ---- COPY writer --------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(HERE, "..", "seed.sql");

class SeedWriter {
  private stream = createWriteStream(OUT_PATH);
  private buf: string[] = [];

  header(sql: string) {
    this.buf.push(`${sql}\n`);
  }

  async row(cols: (string | number)[]) {
    this.buf.push(`${cols.join("\t")}\n`);
    if (this.buf.length >= 8192) await this.flush();
  }

  async endCopy() {
    this.buf.push("\\.\n\n");
    await this.flush();
  }

  private async flush() {
    if (!this.buf.length) return;
    const chunk = this.buf.join("");
    this.buf = [];
    // Respect backpressure: if the buffer is full, wait for it to drain.
    if (!this.stream.write(chunk)) {
      await once(this.stream, "drain");
    }
  }

  async close() {
    await this.flush();
    this.stream.end();
    await once(this.stream, "finish");
  }
}

// ---- Generation ---------------------------------------------------------------

async function main() {
  const w = new SeedWriter();

  // Emit a RAISE NOTICE (with wall-clock time) so the build log shows load
  // progress between tables. RAISE NOTICE goes to the psql client (build stdout);
  // `client_min_messages = notice` below guarantees it isn't filtered.
  const notice = (msg: string) => w.header(`DO $$ BEGIN RAISE NOTICE '[seed %] ${msg}', clock_timestamp(); END $$;`);

  w.header("-- Generated by scripts/generate-seed.ts — do not edit by hand.");
  w.header(`-- parks=${PARK_COUNT} pitches=${PITCHES_MIN}-${PITCHES_MAX} seasons=${SEASONS.join("/")} rngSeed=${RNG_SEED}`);
  w.header("SET client_min_messages = notice;");
  w.header("");
  notice("start");

  let pitchId = 0;
  let vanId = 0;
  let reservationId = 0;

  // park
  notice("loading park");
  w.header("COPY park (id, name) FROM stdin;");
  for (let p = 1; p <= PARK_COUNT; p++) {
    await w.row([p, `Park ${p}`]);
  }
  await w.endCopy();

  // pitch + van are 1:1; buffer vans while emitting pitches, then emit vans.
  // We stream pitches first (one COPY), then vans (another COPY), so collect
  // van rows in memory — ~50k rows is small.
  const vanRows: (string | number)[][] = [];

  notice("loading pitch");
  w.header("COPY pitch (id, park_id, lat, lng) FROM stdin;");
  for (let p = 1; p <= PARK_COUNT; p++) {
    const pitches = randInt(PITCHES_MIN, PITCHES_MAX);
    for (let i = 0; i < pitches; i++) {
      pitchId++;
      // UK-ish coordinates, jittered per pitch.
      const lat = (50 + rng() * 8).toFixed(6);
      const lng = (-5 + rng() * 7).toFixed(6);
      await w.row([pitchId, p, lat, lng]);

      vanId++;
      vanRows.push([vanId, pitchId, MODELS[randInt(0, MODELS.length - 1)], weightedPick(GRADE_WEIGHTS)]);
    }
  }
  await w.endCopy();

  notice("loading van");
  w.header("COPY van (id, pitch_id, model, grade) FROM stdin;");
  for (const row of vanRows) await w.row(row);
  await w.endCopy();

  // reservation — the bulk. Walk each van across each season's open window,
  // booking stays with month-weighted probability.
  notice("loading reservation (the bulk)");
  w.header("COPY reservation (id, van_id, start_date, end_date) FROM stdin;");
  for (let v = 1; v <= vanId; v++) {
    for (const year of SEASONS) {
      let cursor = new Date(Date.UTC(year, 1, 1)); // Feb 1
      const seasonEnd = new Date(Date.UTC(year, 10, 30)); // Nov 30
      while (cursor < seasonEnd) {
        const month = cursor.getUTCMonth() + 1;
        const weight = MONTH_WEIGHT[month] ?? 0;
        if (weight > 0 && rng() < weight) {
          const nights = weightedPick(STAY_LENGTHS);
          const end = addDays(cursor, nights);
          reservationId++;
          await w.row([reservationId, v, fmtDate(cursor), fmtDate(end)]);
          cursor = end; // checkout day is the next booking's earliest start
        } else {
          cursor = addDays(cursor, randInt(2, 6)); // vacancy gap
        }
      }
    }
  }
  await w.endCopy();
  notice("all COPY blocks done");

  // Reset sequences past the explicit ids we inserted.
  w.header(`SELECT setval('park_id_seq', ${PARK_COUNT});`);
  w.header(`SELECT setval('pitch_id_seq', ${pitchId});`);
  w.header(`SELECT setval('van_id_seq', ${vanId});`);
  w.header(`SELECT setval('reservation_id_seq', ${reservationId});`);

  await w.close();

  console.error(`seed.sql written: ${PARK_COUNT} parks, ${pitchId} pitches, ${vanId} vans, ${reservationId} reservations`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
